### PR TITLE
Only import Image if necessary

### PR DESCRIPTION
**Pull request by jordan-heemskerk**

### CODE REVIEW

**Comment by jordan-heemskerk** [comment]
@tkrajina not sure why the build is failing... looks to be a problem with `requests`

I'd like to use the `get_image` numpy functionality in a project but would like to avoid an additional dependency on `Image`/`ImageDraw`.

Thanks

**Comment by jordan-heemskerk** [comment]
@tkrajina bump?

**Comment by tkrajina** [comment]
Merged thanks. The problem with requests is fixed in another pull request (I'm going to merge it in a few minutes).

**Comment by jordan-heemskerk** [comment]
Thanks, any chance you know when a new release will be cut with these changes in place?

**Comment by tkrajina** [comment]
Released it now: https://pypi.python.org/pypi/SRTM.py/0.3.2

**Comment by jordan-heemskerk** [comment]
Awesome, thanks for the quick turnaround!

**Pull request merged**
